
public enum Pieces
{
    EMPTY,
    BLACK_PAWN, BLACK_KNIGHT, BLACK_BISHOP, BLACK_CASTLE, BLACK_QUEEN, BLACK_KING,
    WHITE_PAWN, WHITE_KNIGHT, WHITE_BISHOP, WHITE_CASTLE, WHITE_QUEEN, WHITE_KING;
}
